apiVersion: batch/v1
kind: Job
metadata:
 name: batch-job
spec:
 ttlSecondsAfterFinished: 1
 template:
   metadata:
     labels:
       app: batch-job
   spec:
     restartPolicy: OnFailure
     containers:
       - name: main
         image: luksa/batch-job
